### ISSUE TITLE
HTTPClientFactory.java uses org.apache.http which has been filtered in Android SDK 23 onwards

### ISSUE THREAD

**Issue by VimanyuAgg** [Nexosis/nexosisclient-java#3]
I am getting below error while creating a java client for Android:

09-24 02:19:12.868 15675-15675/com.hypertrack.androidsdkonboarding E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: com.hypertrack.androidsdkonboarding, PID: 15675
                                                                                     java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                         at android.view.View$DeclaredOnClickListener.onClick(View.java:4452)
                                                                                         at android.view.View.performClick(View.java:5198)
                                                                                         at android.view.View$PerformClick.run(View.java:21147)
                                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                      Caused by: java.lang.reflect.InvocationTargetException
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at android.view.View$DeclaredOnClickListener.onClick(View.java:4447)
                                                                                         at android.view.View.performClick(View.java:5198) 
                                                                                         at android.view.View$PerformClick.run(View.java:21147) 
                                                                                         at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                      **Caused by: java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)**
                                                                                         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
                                                                                         at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:964)
                                                                                         at org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56)
                                                                                         at com.nexosis.impl.HttpClientFactory.createClient(HttpClientFactory.java:24)
                                                                                         at com.nexosis.impl.ApiConnection.makeRequest(ApiConnection.java:248)
                                                                                         at com.nexosis.impl.ApiConnection.sendObjectContent(ApiConnection.java:189)
                                                                                         at com.nexosis.impl.ApiConnection.put(ApiConnection.java:151)
                                                                                         at com.nexosis.impl.DataSetClient.create(DataSetClient.java:43)
                                                                                         at com.nexosis.impl.DataSetClient.create(DataSetClient.java:32)

**Comment by jm0nty** [comment]
Removed  org.apache.http lib for Google's HTTP com.google.http-client.
